#backend:
#  name: netlify-api
#  url: http://localhost:8080

backend:
  name: bitbucket
  repo: marcusclements/blockdoxcom # Change this to your repo
  branch: master
  auth_type: implicit
  app_id: r7ZAM4TSLSLfAUkq2D

#production:
#  backend:
#    name: bitbucket
#    repo: marcusclements/blockdoxcom # Change this to your repo
#    branch: master
#    auth_type: implicit
#    app_id: r7ZAM4TSLSLfAUkq2D

media_folder: "content/images" # Folder where user uploaded files should go
public_folder: "content/images"

collections: # A list of collections the CMS should be able to edit
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "content/articles" # The path to the folder where the documents are stored
#    format: markdown-python
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "entry-title"}
      - {label: "Body", name: "body", widget: "markdown"}
#    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "General"}
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "content/pages/about.md"
#        format: markdown-python
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

